server:
  port: 8083
spring:
  application:
    name: report-service
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/report_service_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,info
